//
   
/*
 * Copyright (c) 2022 Daniel Lockhead <daniel.lockhead@videotron.ca>
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef _FUNCTADV_H_
#define _FUNCTADV_H_



//#include "scpi/scpi.h"


// define ressource used by ADC
#define ADC0    26
#define ADC1    27
#define ADC2    28
#define ADC3    29
#define ADC_REF 3.0f  // reference voltage generated by device  LM4040

//define limit for DAC
#define MINDACVOLT  0     // minimum voltage for the MCP4725 DAC
#define MAXDACVOLT  3.3   // maximum voltage for the MCP4725 DAC


#define NOERR    0      // No error
#define EOOR     1      // Flag for Error for data out of range
#define EDE      2     // SCPI_ERROR_DEVICE_ERROR


void    read_int_ADC(float *adc_val);
void    setup_ADC(bool enable);
void    read_ADC(float *adc_val);
uint8_t dac_set(float value,bool save);
float   read_master_adc(uint8_t channel);
float   read_power(uint8_t mode);
void    calibrate_power(float actual, float expected);



#endif //

void scan_i2c_bus();

