//
   
/*
 * Copyright (c) 2022 Daniel Lockhead <daniel.lockhead@videotron.ca>
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef _FUNCTADV_H_
#define _FUNCTADV_H_

#include "hardware/i2c.h"

//#include "scpi/scpi.h"


// define ressource used by ADC
#define ADC0    26
#define ADC1    27
#define ADC2    28
#define ADC3    29
#define ADC_REF 3.0f  // reference voltage generated by device  LM4040

//define limit for DAC
#define MINDACVOLT  0     // minimum voltage for the MCP4725 DAC
#define MAXDACVOLT  3.3   // maximum voltage for the MCP4725 DAC

// Error Flag used on EEprom 
#define NOERR    0      // No error
#define EOOR     1      // Flag for Error for data out of range
#define EDE      2      // SCPI_ERROR_DEVICE_ERROR
#define ERE      3      // SCPI_ERROR_MASS_STORAGE_ERROR,
#define ECE      4      //SCPI_ERROR_CHARACTER_DATA_ERROR
#define EMP      5      //SCPI_ERROR_MISSING_PARAMETER;
#define EIVN     6      //SCPI_ERROR_ILLEGAL_VARIABLE_NAME;
#define ENDE     7      //SCPI_ERROR_NUMERIC_DATA_ERROR
#define EBE      8      // Read Byte Error



// define address location on eeprom

#define ADD_EEPROM_BASE    0x40      // EEprom base adress to start
#define TEST_EEPROM_ADD    0x0       // EEprom address used during selftest
#define EE_PAGESIZE        32        // Pagesize 
#define EEMODEL            32        // 24lc32 eeprom
#define EESIZE             4096        // 24lc32 eeprom

#define min(a, b) ((a) < (b) ? (a) : (b))

void    read_int_ADC(float *adc_val);
void    setup_ADC(bool enable);
void    read_ADC(float *adc_val);
uint8_t dac_set(float value,bool save);
float   read_master_adc(uint8_t channel);
float   read_power(uint8_t mode);
void    calibrate_power(float actual, float expected);
uint8_t cfg_eeprom_rw(char mode, uint32_t eeaddr,uint8_t eedatalen, char* data, uint8_t datalen);
void    scan_i2c_bus(i2c_inst_t* i2c);
uint8_t cfg_eeprom_read_full();
uint8_t cfg_eeprom_write_default();
uint8_t stringtonumber(const char *str, long *result);
bool Boot_check(void);
bool Board_Selftest();



#endif //



